---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 2-example2-helm-release-git-helm-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 2-example2-source-git-helm-app
  interval: 10s
  targetNamespace: example-2
  values:
    labels:
      app:
        env: dev
        name: nginx
        version: 0.0.2
    namespace:
      name: example-2
    replicaCount: 1
    service:
      nodePort: 30002
      type: NodePort
