---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 3-example3-source-oci-helm-app
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: ghcr-auth
  type: oci
  url: oci://ghcr.io/akashicloud/fluxcd-examples
