---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 3-example3-helm-release-oci-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: fluxcd-examples-helm-app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: 3-example3-source-oci-helm-app
      version: 0.0.3
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: example-3
  values:
    labels:
      app:
        env: dev
        name: nginx
        version: 0.0.2
    namespace:
      name: example-3
    replicaCount: 1
    service:
      nodePort: 30003
      type: NodePort
